### PR TITLE
Update LBVersion description

### PR DESCRIPTION
**Pull request by jannyHou**
Connect to strongloop-internal/scrum-loopback#1124

### CODE REVIEW

**Comment by jannyHou** [comment]
Reword LBVersion description due to 3.x release:
According to 
```
Add back a version prompt

    2.x (long term support)
    3.x (current)
```

PTAL @bajtos . Thanks.

cc @0candy

**Comment by jannyHou** [comment]
I am taking out my windows laptop from cabinet and will look into windows failure 😉

**Comment by eddiemonge** [comment]
use a vm. much easier.

**Comment by bajtos** [comment]
The change LGTM, but we should not land it until 3.0 moves from RC to GA.

Right now, 3.0 is a release candidate, therefore the current description "pre-release" is correct.

**Comment by bajtos** [comment]
See also https://github.com/strongloop/loopback/issues/2821

**Comment by bajtos** [comment]
CI is acting up today. `npm test` is passing locally, I am going ahead to merge this patch.

**Pull request merged**
