### PR TITLE
Add host and port to start app response payload

### PR DESCRIPTION
**Pull request by seanbrookes**
- the arc ui needs it to provide a link to the running app

connected to: strongloop/strong-arc#1484

### CODE REVIEW

**Comment by seanbrookes** [comment]
test please

**Comment by rmg** [comment]
@slnode test please

**Comment by seanbrookes** [comment]
@slnode test please

**Comment by seanbrookes** [comment]
test please

**Comment by bajtos** [comment]
LGTM.

Would you like to review this yourself @ritch too, or are we good to merge?

**Comment by seanbrookes** [comment]
@ritch PTAL

**Comment by ritch** [comment]
LGTM

**Pull request merged**
