### PR TITLE
Update translation files - round#2

### PR DESCRIPTION
**Pull request by 0candy**
https://github.com/strongloop-internal/scrum-loopback/issues/1097

### CODE REVIEW

**Comment by jannyHou** [comment]
Confirmed that it fails on time out error, not related to this pr. We can merge it.
```
Error: timeout of 10000ms exceeded.
```

**Comment by Amir-61** [comment]
was workspace missing translation for Chinese previously? It seems now they are new files in this PR!

**Comment by 0candy** [comment]
weird, it's there in the previous PR https://github.com/strongloop/loopback-workspace/pull/323/files

**Comment by jannyHou** [comment]
@Amir-61 Good catch. My bad, the file name should be `zh-Hans` and `zh-Hant` not underscore one. I will submit a pr to fix them later.

**Comment by jannyHou** [comment]
Wrong files removed. Will squash commits if they look good to @0candy @Amir-61 . Thanks.

**Comment by 0candy** [comment]
@jannyHou LGTM

**Comment by Amir-61** [comment]
@jannyHou LGTM; please squash your commits as one single commit before landing. 🚢

**Pull request merged**
