### PR TITLE
Adding useNewUrlParser option for mongodb available for v3.1 and above

### PR DESCRIPTION
**Pull request by iamjamilspain**
### Description
Added useNewUrlParser which is 
option needed for v3.1 and above

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by jamilhassanspain** [comment]
> @jamilhassanspain Hmm, the commit message has some problem:
> 
> ```
> **************************************************
> **
> **  Linting commit logs
> **
> **  1 problems found:
> **    914b5b7 - Adding useNewUrlParser option for mongodb available: First line should be 50 characters or less (saw 70)
> **
> **************************************************
> ```
> 
> Could you fix it? Thanks, then I will help you land the PR.

Not sure how to fix this.  I tried to push a complete new update.  Not sure if that worked.

**Comment by dhmlau** [comment]
@jamilhassanspain, can you try this instruction to amend the commit message (using `git commit --amend`)? 
https://help.github.com/articles/changing-a-commit-message/

**Comment by dhmlau** [comment]
@slnode test please

**Comment by dhmlau** [comment]
CLA check seems to be stuck. kicking it off again. 
@slnode test please

**Comment by dhmlau** [comment]
@iamjamilspain , thanks for your contribution.  Your PR has landed. 🎉

**Pull request merged**
