### PR TITLE
added cors middleware

### PR DESCRIPTION
**Pull request by claylo**
Enables CORS across the entire loopback application, using reasonable defaults. 

See https://github.com/strongloop/loopback/issues/575

### CODE REVIEW

**Comment by bajtos** [comment]
@claylo ping, are you still keen to get this landed?

**Comment by claylo** [comment]
@bajtos I am! I'll work on this today.

**Comment by bajtos** [comment]
@claylo ping, have you managed to make any progress?

**Comment by claylo** [comment]
@bajtos I'm actually working on this now. Sorting out new test case addition on strong-remoting, and expect to submit PR today.

**Comment by bajtos** [comment]
>  I'm actually working on this now. Sorting out new test case addition on strong-remoting, and expect to submit PR today.

Cool, I am glad to hear that! Please don't submit a new PR, just add more commits to this one. Rewriting the git history is ok too, in case that works better for you.

**Comment by claylo** [comment]
@bajtos I should have been more specific—I meant a PR on strong-remoting. :)

**Comment by claylo** [comment]
@bajtos I think we're good to go on this now.

**Comment by bajtos** [comment]
The strong-remoting PR: https://github.com/strongloop/strong-remoting/pull/165

@claylo when you are pulling changes from master to a feature branch, you need to run `git rebase master` instead of `git pull`/`git merge`. That way GitHub shows only the relevant commits in the diff. At the moment, the diff contains too many unrelated changes.

Could you please run the following commands  clean this up?

 1. fetch latest changes from strongloop/loopback-workspace to your master branch
 2. `git rebase master && git push -f`

**Comment by bajtos** [comment]
The commit 779a40119b0090b399f903483e1118d0ea26ccf7 does not look right to me, it looks like it contains changes made in master and not related to this PR. Could you please check?

It may be better to run `git rebase -i` instead of `git rebase` and remove that commit.

**Comment by bajtos** [comment]
@claylo what's the status of this pull request? Are you still keen to get it finished and landed?

**Comment by bajtos** [comment]
Closing in favour of https://github.com/strongloop/loopback-workspace/pull/192.

**Pull request closed without merging**
