### PR TITLE
Fix node 8 compatibility

### PR DESCRIPTION
**Pull request by horstmannmat**
Signed-off-by: Matheus Horstmann <mch15@inf.ufpr.br>

#### Related issues
#535 

### Checklist

- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by jannyHou** [comment]
@slnode test please

**Comment by horstmannmat** [comment]
I am not able to see the details, and fix it: "The connection has timed out"

**Comment by jannyHou** [comment]
@horstmannmat Don't worry the failed module is an internal one and the failure is not related to your PR.
I am going to approve and merge it.

**Pull request merged**
