### PR TITLE
package.json: Update fs-extra

### PR DESCRIPTION
**Pull request by mc10**
Fixes the issues mentioned in jprichardson/node-jsonfile#26.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by raymondfeng** [comment]
ok to test

**Comment by raymondfeng** [comment]
There seems to be breaking API: 
```
TypeError: Object #<Object> has no method 'readJsonFileSync'
    at Object.<anonymous> (/mnt/jenkins/workspace/loopback-workspace.pr/a88e4f2b/models/config-file.js:9:719)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions.(anonymous function) [as .js] (/mnt/jenkins/workspace/loopback-workspace.pr/a88e4f2b/node_modules/build-framework/node_modules/istanbul/lib/hook.js:107:24)
```

Can you check?

**Comment by mc10** [comment]
Seems like the function was renamed to [`readJsonSync`](https://github.com/jprichardson/node-fs-extra#readjsonfile-options-callback).

**Comment by raymondfeng** [comment]
ok to test

**Comment by raymondfeng** [comment]
Reworked on https://github.com/strongloop/loopback-workspace/issues/219

**Pull request closed without merging**
