### PR TITLE
remove 2.x from available LB versions

### PR DESCRIPTION
**Pull request by dhmlau**
### Description
Related to https://github.com/strongloop/loopback/issues/4180

- Remove 2.x from available LB versions
- Remove tests related to 2.x and making the default LB version to test is 3.x.

### CODE REVIEW

**Comment by dhmlau** [comment]
There are 2 failed test cases. Both are related to the change of the default version from 2.x to 3.x:
In lib/helper.js
```
exports.DEFAULT_LB_VERSION = '3.x';
```

```
 1) end-to-end
16:43:14        empty-server template
16:43:14          has legacy explorer disabled in config:
16:43:14      AssertionError: legacyExplorer option: expected undefined to be false
16:43:14   
16:43:14 
16:43:14   2) ModelMethod
16:43:14        correctly adds new method:
16:43:14      Uncaught AssertionError: expected {} to have a property 'isStatic'
16:43:14       at /home/jenkins/workspace/nb/loopback-workspace~master/3ed5ebba/test/model-method.js:59:48
16:43:14       at /home/jenkins/workspace/nb/loopback-workspace~master/3ed5ebba/node_modules/async/dist/async.js:473:16
16:43:14       at next (node_modules/async/dist/async.js:5329:29)
16:43:14       at /home/jenkins/workspace/nb/loopback-workspace~master/3ed5ebba/node_modules/async/dist/async.js:969:16
16:43:14       at setup (common/models/config-file.js:90:7)
16:43:14       at nextTask (node_modules/async/dist/async.js:5324:14)
16:43:14       at next (node_modules/async/dist/async.js:5331:9)
```

**Comment by dhmlau** [comment]
@raymondfeng @bajtos @jannyHou, you might have more knowledge in this repo.  When testing locally, the 2 failed test cases happen only when I change the default LB version to be 3.x (they pass when 2.x is the default version).  I'm wondering whether the 2 tests are valid for 3.x.  Thanks!

**Comment by bajtos** [comment]
```
2) ModelMethod
16:43:14        correctly adds new method:
16:43:14      Uncaught AssertionError: expected {} to have a property 'isStatic'
```

We changed the way how static/prototype methods are distinguished in LB3. See https://loopback.io/doc/en/lb3/3.0-Release-Notes.html#name-indicates-whether-method-is-static

Ideally, I think there should be two tests:
 - One adding a static method
 - The other adding a prototype methods

The tests should verify the key created in `methods` object, e.g. `testMethod` for a static method and `prototype.testMethod` for a prototype method.

IIRC, loopback-workspace is still supporting `isStatic` flag in its API, see https://github.com/strongloop/loopback-workspace/blob/6d6246777f5cb94b313d69793408a322f1d99564/common/models/model-method.js#L15-L33

I would expect that we already have tests to verify handling of LB3 remote methods, so maybe the failing test can be safely removed? IDK, please check yourself.

```
      empty-server template
          has legacy explorer disabled in config:
      AssertionError: legacyExplorer option: expected undefined to be false
```

I don't remember what is `legacyExplorer` used for. However, we do have a test to verify that LB 3.x projects don't set that flag, see here:

https://github.com/strongloop/loopback-workspace/blob/14a52234861ee96c41655493f549d9985f66aeaa/test/end-to-end.js#L565

I think the test `empty-sever template has legacy explorer disabled in config` can be safely removed as part of this pull request.

**Comment by dhmlau** [comment]
Thanks @bajtos. I've removed test case `empty-sever template has legacy explorer disabled in config` as you suggested. 
For `Model method correctly adds new method`, I found the test case listed here: 
https://github.com/strongloop/loopback-workspace/blob/master/test/model-method.js#L206-L236 look for the `isStatic` flag in a different place as mentioned in the docs: https://loopback.io/doc/en/lb3/3.0-Release-Notes.html#name-indicates-whether-method-is-static.  Therefore, I've removed it as well. 
Thanks!

**Comment by dhmlau** [comment]
Confirmed with @smartmouse, 2.x was removed since APIC v5.0.8.6, and was never in APIC v2018.

**Comment by dhmlau** [comment]
Will fix the downstream failure in `generator-loopback` repo.

**Pull request merged**
