### PR TITLE
fix etag bug with xhr in chrome 52.

### PR DESCRIPTION
**Pull request by anthonyettinger**
disable etag for workspace endpoint until
chrome fixes xhr 304/etag bug.

See https://bugs.chromium.org/p/chromium/issues/detail?id=633696
https://github.ibm.com/apimesh/scrum-api-editor/issues/788

@kraman PTAL
@ritch PTAL

### CODE REVIEW

**Comment by jtary** [comment]
@slnode test please

**Comment by rmg** [comment]
It is odd how these tests are so much more flaky on older versions of node. I wonder if there are some poorly written `*Sync` shims being used in some of the test code.

**Comment by anthonyettinger** [comment]
test please

**Comment by anthonyettinger** [comment]
fixing this in apim-ui instead.

**Pull request closed without merging**
