### PR TITLE
Use "^3.0.0" when scaffolding LoopBack 3.x apps

### PR DESCRIPTION
**Pull request by bajtos**
Connect to strongloop-internal/scrum-loopback#1063

### CODE REVIEW

**Comment by bajtos** [comment]
Windows CI failures are due to https://github.com/strongloop/loopback-workspace/issues/322, I'll ignore them.

**Comment by bajtos** [comment]
https://cis-jenkins.swg-devops.com/job/nb/job/loopback-workspace~master/label=nvm%20&&%20dbs,nodeVersion=0.12/180/console
>  1) end-to-end start/stop/restart restarts the app:
     Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.
      at null.<anonymous> (node_modules/loopback/node_modules/loopback-context/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31)

@0candy Is that ^^^ a known issue?

**Comment by bajtos** [comment]
@slnode test please

**Comment by 0candy** [comment]
Yes, I have seen that timeout issue before. Extending the timeout fixes it.
https://github.com/strongloop/loopback-workspace/pull/311

**Pull request merged**
