### PR TITLE
[WebFM] pt_BR translation Check-in by Austin Chang (austinhc@tw.ibm.com)

### PR DESCRIPTION
**Pull request by candytangnb**
Portuguese(Brazil) translation check-in by Austin Chang (austinhc@tw.ibm.com) using WebFM tool.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by dhmlau** [comment]
@slnode test please

**Comment by dhmlau** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by dhmlau** [comment]
@slnode test please

**Comment by dhmlau** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Pull request merged**
