### PR TITLE
Fix eslint setup in empty-server template

### PR DESCRIPTION
**Pull request by superkhau**
Connect to https://github.com/strongloop/loopback-workspace/issues/310

@bajtos PTAL

### CODE REVIEW

**Comment by bajtos** [comment]
The patch LGTM, but the CI builds are failing. Please check what's going on.

**Comment by superkhau** [comment]
@slnode test please

**Comment by superkhau** [comment]
@rmg Do you know why some of the builds are timing out?

**Comment by superkhau** [comment]
I'm thinking `npm install` is taking too long on CI (because it takes awhile even locally).

**Comment by superkhau** [comment]
@0candy @jannyHou Maybe you can give me a hand here. Does `npm test` fail for you locally too (master)?

**Comment by jannyHou** [comment]
@0candy already sent a pr to fix CI, and I believe the timeout failure and dir conflict on node0.10 platforms are same one as:
https://github.com/strongloop/loopback-workspace/pull/311#issuecomment-238892681

The basic idea is globalization slows down test case as Miroslav mentioned, then some test case fails due to timeout error, other tests run after the timeout one fails due to dir conflict error.

The dir conflict error is reproducible on local with node 0.10.

**Comment by superkhau** [comment]
@jannyHou Can you link the PR fix to this issue so I can track when it gets merged?

**Comment by jannyHou** [comment]
Sure. PR to fix it: 
https://github.com/strongloop/loopback-workspace/pull/311

**Pull request merged**
