### PR TITLE
Enable "validateUpsert" for newly created models

### PR DESCRIPTION
**Pull request by bajtos**
Connect to strongloop/loopback-datasource-juggler#262

/to @raymondfeng or @ritch please review

### CODE REVIEW

**Comment by raymondfeng** [comment]
The patch LGTM. But in general, we need to have a way to roll out `semi-breaking` changes so that we can make them default in next major release.  Introducing a flag for each thing is annoying.

**Comment by bajtos** [comment]
@slnode test pleaes

**Comment by bajtos** [comment]
@slnode test please

**Comment by bajtos** [comment]
> But in general, we need to have a way to roll out semi-breaking changes so that we can make them default in next major release. 

At the moment, I am keeping a GH issue with a list of things to remove: https://github.com/strongloop/loopback/issues/1224

> Introducing a flag for each thing is annoying.

I agree it's a bit annoying, but I don't have any better solution. Do you have one?

**Pull request merged**
