### PR TITLE
Fix eslint infrastructure

### PR DESCRIPTION
**Pull request by bajtos**
- Run eslint directly, bypass Grunt
 - Fix linter issues

@0candy please review

Related: https://github.com/strongloop/loopback-workspace/pull/294#issuecomment-228878173

cc: @loay @rmg

### CODE REVIEW

**Comment by rmg** [comment]
👍  thanks for fixing the missing `eslint`.

**Comment by rmg** [comment]
Since the failures are unrelated to these changes, but these changes are needed for #294, should this be merged now so that #294 can be rebased? Or should this PR be closed and the changes from here be pulled in to #294?

**Comment by loay** [comment]
IMO, this PR should be merged first, so when I rebase the other PR, we make sure that all tests are passing.

**Comment by 0candy** [comment]
LGTM :+1:

**Pull request merged**
