### PR TITLE
Support flag to exclude inheritance of base properties

### PR DESCRIPTION
**Pull request by raymondfeng**
/to @ritch 

Fix for https://github.com/strongloop/loopback-workspace/issues/223

### CODE REVIEW

**Comment by raymondfeng** [comment]
It also fixes https://github.com/strongloop/loopback/issues/1325

**Comment by raymondfeng** [comment]
Maybe a better way to exclude properties from being inherited from base is to add a separate attribute to the model definition, for example:

```js
{
  name: 'MyModelWithoutId',
  properties: {
  },
  base: 'PersistedModel',
  excludedBaseProperties: ['id']
}
```

**Comment by raymondfeng** [comment]
Connect to #223

**Comment by ritch** [comment]
Why do we even need this?

**Comment by ritch** [comment]
Had an offline discussion with @raymondfeng.

LGTM

**Comment by raymondfeng** [comment]
ok to test

**Pull request merged**
