### PR TITLE
Fix Run loopback workspace server with 'node .' (ISSUE#234)

### LINKED ISSUE #234: Run loopback-workspace server on 'node .'
'node .' command does not start the loopback-workspace server.

### PR DESCRIPTION
**Pull request by gunjpan**
Resolves #234

### CODE REVIEW

**Comment by gunjpan** [comment]
@bajtos : Please review

**Comment by bajtos** [comment]
The code LGTM. @gunjpan Could you please improve the commit message - remove capital case, remove link to issue number and make sure the first line fits to 50 characters?

**Comment by bajtos** [comment]
In case you are not familiar with git history manipulation: `git commit --amend` and `git push -f` are the commands to run.

**Comment by gunjpan** [comment]
@bajtos : Please review commit message.

**Comment by bajtos** [comment]
Looks good. We usually don't include references to issues/pull requests in commits, as that creates a new crosslink after each rebase/history rewrite.

**Comment by bajtos** [comment]
@slnode test please

**Comment by bajtos** [comment]
Landed, thank you.

**Comment by gunjpan** [comment]
@bajtos Thank you!

**Pull request merged**
