### PR TITLE
[WebFM] de/es/it/ja/ko/tr/zh_CN/zh_TW translation Check-in by Austin Chang (austinhc@tw.ibm.com)

### PR DESCRIPTION
**Pull request by candytangnb**
German(Germany), Spanish(Spain), Italian(Italy), Japanese, Korean(Korea), Turkish, Simplified Chinese, Traditional Chinese translation check-in by Austin Chang (austinhc@tw.ibm.com) using WebFM tool.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by dhmlau** [comment]
@slnode test please

**Comment by dhmlau** [comment]
@slnode test please
it says cannot find module `strong-globalize`. retrying it again.

**Comment by dhmlau** [comment]
@slnode test please

**Comment by dhmlau** [comment]
@candytangnb , as discussed, you'll be creating another PR with all other translated files in it.  With this reason, I'm closing this PR.  Thanks.

**Pull request closed without merging**
