### PR TITLE
Add url to datasource config

### PR DESCRIPTION
**Pull request by jannyHou**
Connect to strongloop/loopback#2089

This pr has to be merged after all changes in `generator-loopback` and other connectors are landed

Add url to:
- [x] mysql
- [x] mssql
- [x] mongodb
- [x] postgresql

Add dsn to:
- [x] db2

Add tns to:
- [x] oracle

### CODE REVIEW

**Comment by jannyHou** [comment]
@bajtos please review it :) thank you

**Comment by bajtos** [comment]
@jannyHou could you please add `description` fields, where you explain to the user that the url/dsn field will overwrite all other settings and also include an example value to use.

It would be great if you could check what the output (prompt) looks like when running `yo loopback:datasource` (or `apic` or `slc`) .

**Comment by jannyHou** [comment]
@bajtos good idea! I think that would take place in `generator-loopback`, I mean adding description.

**Comment by jannyHou** [comment]
Output when run `slc loopback:datasource`
```

C:\Users\IBM_ADMIN\Desktop\loopback-projects\connectors\appDS>slc loopback:datas
ource
? Enter the data-source name: trydb2
? Select the connector for trydb2: IBM DB2 (supported by StrongLoop)
Connector-specific configuration:
? Connection String dsn (override other settings): DATABASE=MY_DB;HOSTNAME=MY_H
OST;PORT=MY_PORT;PROTOCOL=TCPIP;UID=MY_UID;PWD=MY_PWD
? host:

C:\Users\IBM_ADMIN\Desktop\loopback-projects\connectors\appDS>slc loopback:datas
ource
? Enter the data-source name: trycloudant
? Select the connector for trycloudant: IBM Cloudant DB (supported by StrongLoo
p)
Connector-specific configuration:
? Connection String url (override other settings): https://username:password@ho
st
? database:


C:\Users\IBM_ADMIN\Desktop\loopback-projects\connectors\appDS>slc loopback:datas
ource
? Enter the data-source name: trymongodb
? Select the connector for trymongodb: MongoDB (supported by StrongLoop)
Connector-specific configuration:
? Connection String url (override other settings): mongodb://username:password@
hostname:port/database
? host:

C:\Users\IBM_ADMIN\Desktop\loopback-projects\connectors\appDS>slc loopback:datas
ource
? Enter the data-source name: trymysql
? Select the connector for trymysql: MySQL (supported by StrongLoop)
Connector-specific configuration:
? Connection String url (override other settings): mysql://user:pass@host/db
? host:

C:\Users\IBM_ADMIN\Desktop\loopback-projects\connectors\appDS>slc loopback:datas
ource
? Enter the data-source name: trypostgresql
? Select the connector for trypostgresql: PostgreSQL (supported by StrongLoop)
Connector-specific configuration:
? Connection String url (override other settings): postgres://username:password
@localhost/database
? host:

C:\Users\IBM_ADMIN\Desktop\loopback-projects\connectors\appDS>slc loopback:datas
ource
? Enter the data-source name: tryoracle
? Select the connector for tryoracle: Oracle (supported by StrongLoop)
Connector-specific configuration:
? Connection String tns: (DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=MY_HOST)(POR
T=MY_PORT))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=MY_DB)))
? host:


C:\Users\IBM_ADMIN\Desktop\loopback-projects\connectors\appDS>slc loopback:datas
ource
? Enter the data-source name: trymssql
? Select the connector for trymssql: Microsoft SQL (supported by StrongLoop)
Connector-specific configuration:
? Connection String url (override other settings): mssql://username:password@lo
calhost/database
? host:

```

**Comment by bajtos** [comment]
@jannyHou looks good in general, could you please reword the prompt? I think something like the following would be better:

```
Connection string url to override all other settings (e.g. https://username:password@host)
```

(Please apply the change to all entries.)

**Comment by bajtos** [comment]
LGTM, please squash the commits before landing.

**Comment by jannyHou** [comment]
@slnode test please

**Comment by jannyHou** [comment]
@slnode test please

**Pull request merged**
