### PR TITLE
update dependencies and fix eslint violations

### PR DESCRIPTION
**Pull request by nabdelgadir**
#### Related issues

- connect to https://github.com/strongloop-internal/scrum-apex/issues/425

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by nabdelgadir** [comment]
CI failure existed before changes.

**Comment by nabdelgadir** [comment]
@dhmlau 
> CI failure existed before changes.

They're not related. 

> as a follow up PR, we might want to remove the tests with Node.js 4 and 6.

Which file can I remove it from?

**Comment by dhmlau** [comment]
About removing Node.js 4 and 6 from CI, it's strange. I looked at `package.json` and it says `>= 8` for node version already.

**Comment by nabdelgadir** [comment]
> About removing Node.js 4 and 6 from CI, it's strange. I looked at `package.json` and it says `>= 8` for node version already.

@dhmlau Maybe it's in the repo settings?

**Comment by nabdelgadir** [comment]
@slnode test please

**Pull request merged**
