### PR TITLE
update strong-error-handler test cases

### PR DESCRIPTION
**Pull request by loay**

### CODE REVIEW

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
Now that I've got mysql in the test environment, the failures are being caused by `eslint` not being a dev dependency. The StrongLoop CI never saw this problem because `posttest` never gets triggered in that environment.

**Comment by loay** [comment]
@rmg Thanks for your help

**Comment by bajtos** [comment]
> Now that I've got mysql in the test environment, the failures are being caused by `eslint` not being a dev dependency. The StrongLoop CI never saw this problem because `posttest` never gets triggered in that environment.

I opened a pull request to fix that, see https://github.com/strongloop/loopback-workspace/pull/297

**Comment by loay** [comment]
Some tests failing on PR #297 because of the issue (test cases) that I am addressing in this PR. 
environments are overlapping so I separated them in this PR. 
Can one of you review: @bajtos or @0candy 
Thanks.

**Comment by rmg** [comment]
@loay the commits in this PR are nice and small, which is great, but their commit messages aren't very helpful for figuring out _why_ the change in each commit is being made.

**Comment by loay** [comment]
@rmg I was just trying to see if the fix I apply would work with jenkins. They were working fine locally but not on jenkins. I am squashing them anyways as they are irrelevant

**Comment by loay** [comment]
@slnode test please

**Comment by loay** [comment]
@slnode test please

**Comment by loay** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by loay** [comment]
@slnode test please

**Comment by bajtos** [comment]
@loay as we discussed in Toronto, the test-cases for error handling should be grouped together in one place, as I am doing in #298. Let's close this pull request in favour of mine.

**Pull request closed without merging**
